#!/usr/bin/env python3
import datetime
import serial

ser = serial.Serial(
    port='/dev/ttyAMA0',
    baudrate = 115200,
    timeout=0  #Attempting to time gate the pattern
#   parity=serial.PARITY_NONE,
#   stopbits=serial.STOPBITS_TWO,#35B (minus 6 bits) with two stop bits
#   bytesize=serial.EIGHTBITS,  # 38 bytes with one stop bit

    )

len = 100
num_collects_end = 1000
num_collects = 0

values = {}

while (num_collects < num_collects_end):
    data=ser.read(len)
    if (data): #Don't print empty lines
        data_hex = data.hex()
        if data_hex in values:
            values[data_hex] += 1
        else:
            values[data_hex] = 1
        num_collects += 1

print(values)
